# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(default='not read', max_length=10),
        ),
    ]
